export type NavigationAPIResponse = {
	place_id: number;
	license: string;
	osm_type: "node" | "way" | "relation";
	osm_id: number;
	lat: string;
	lon: string;
	place_rank: number;
	category: string;
	type: string;
	importance: number;
	addresstype: string;
	name: string | null;
	display_name: string;
	address: {
		house_number: string;
		house_name: string;
		region: string;
		state: string;
		state_district: string;
		county: string;
		road: string;
		suburb: string;
		municipality: string;
		town: string;
		village: string;
		district: string;
		borough: string;
		subdivision: string;
		city: string;
		"ISO3166-2-lvl8": string;
		city_district: string;
		postcode: string;
		country: string;
		country_code: string;
		neighbourhood: string;
	};
	bounding_box: number[];
};
