name: Release

on:
  push:
    branches: [beta]
    paths-ignore: ["**.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: beta
          fetch-depth: "0"
      - run: git fetch --depth=1 origin beta +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Install"
        run: npm install
      - name: "Build"
        run: npm run build
      - name: "Version"
        run: npx semantic-release
