name: release

on:
  push:
    branches: [main]
    paths-ignore: ["**.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: "0"
      - run: git fetch --depth=1 origin main +refs/tags/*:refs/tags/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: "Install"
        run: yarn install
      - name: "Build"
        run: yarn run build
      - name: "Version"
        run: npx semantic-release
      - name: "Get latest tag"
        run: export LATEST_TAG=$(git describe --abbrev=0 --tags)
      - name: "Build docker"
        run: "docker build -t turnazos/storage ./"
      - name: "Docker tag"
        run: docker tag turnazos/storage ghcr.io/turnazos/storage:$LATEST_TAG
      - name: "Docker push"
        run: docker push ghcr.io/turnazos/storage:$LATEST_TAG && docker push ghcr.io/turnazos/storage:latest
